name: BrowserStorage
on: push
jobs:
  verify:
    name: Run test and coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 7.11.0
          cache: pnpm
      - uses: actions/node-setup@v3
        with:
          node-version: '16.16.0'
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm test:pnpm:coverage
  build:
    needs: verify
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - run: pnpm build